name: Generate example site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-site:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://patrickdappollonio.github.io/http-server-testing-page/"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up http-server
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: patrickdappollonio/http-server
          platform: linux
          arch: x86_64

      - name: Run http-server and create a copy of the website
        run: |
          set -e
          rm -rf .git/ .github/ output/
          mkdir /tmp/output
          message='This is a testing page for [`http-server`](https://github.com/patrickdappollonio/http-server). For more information, visit the official repository.'
          http-server -p 8080 --banner "$message" &
          SERVER_PID=$!
          sleep 5
          cd /tmp/output && wget -r -k -E -p --restrict-file-names=windows -nH "http://localhost:8080/"
          kill -9 $SERVER_PID || true

      - name: Upload artifacts to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
